### ISSUE TITLE
Hangs indefinitely

### ISSUE THREAD

**Issue by stevensacks** [christopherthielen/check-peer-dependencies#1]
I am editing this ticket because it seems that it has nothing to do with that package. Even when that package has been removed entirely, it still hangs.

```
npx check-peer-dependencies --yarn --install
npx: installed 44 in 3.597s
// I waited over a minute at this point before I killed the process
^C
```

If you can add a `--debug` flag to help determine why it's hanging, I can let you know what it says.

**Comment by christopherthielen** [comment]
Will you try again with the latest version?
