### ISSUE TITLE
--install installs everything as non-dev dependency

### ISSUE THREAD

**Issue by openreply-dleinhaeuser** [christopherthielen/check-peer-dependencies#21]
When using `check-peer-dependencies --install` it properly identifies and installs missing peer dependencies, however peer dependencies of dev-dependencies are not installed as dev-dependencies.

## Example:
`> npm install --save-dev eslint-config-airbnb` on a freshly initialized otherwise empty project complains about missing peer dependencies

## Expected behavior
`> npx check-peer-dependencies --install` installs missing peer dependencies of `eslint-config-airbnb` as dev-dependencies since it is itself a dev-dependency

## Actual behavior
`> npx check-peer-dependencies --install` installs missing peer dependencies of `eslint-config-airbnb` as non-dev dependencies

**Comment by christopherthielen** [comment]
check-peer-dependencies does [attempt to install as devDependencies](https://github.com/christopherthielen/check-peer-dependencies/blob/47d40ef14303f9f32e210375ecadf5be7e80fdb5/src/packageManager.ts#L31-L33) if the [peer dep is from a devDependency](https://github.com/christopherthielen/check-peer-dependencies/blob/0493379e0d49fd93f5e8bfb9e69d1fc8396cc9a7/src/solution.ts#L24-L31).  Something must not be working correctly.

**Comment by christopherthielen** [comment]
note to self: `npm install --save-dev eslint-config-airbnb` installs all peer dependencies now (npm 8) so to reproduce, delete `node_modules/eslint`

**Comment by christopherthielen** [comment]
I misread the code, this isn't currently implemented.  I agree it is the proper/desired behavior
